name: Linter

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod" # Use Go version from your project

      - name: Check gofmt
        run: |
          gofmt -l . | tee fmt-out.txt
          if [ -s fmt-out.txt ]; then
            echo "The following files are not formatted correctly:"
            cat fmt-out.txt
            echo "Please run: go fmt ./..."
            exit 1
          fi
